/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DiscordSyntaxPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_view3 = require("@codemirror/view");

// src/spoiler-post-processor.ts
function processSpoilers(element, doc = element.ownerDocument) {
  function createSpoilerSpan() {
    const spoilerSpan = element.createEl("span", {
      cls: "note-flow-spoiler discord-syntax-spoiler",
      attr: {
        role: "button",
        tabindex: "0",
        "aria-expanded": "false",
        "aria-label": "Spoiler, click to reveal"
      }
    });
    if (spoilerSpan.parentNode) {
      spoilerSpan.parentNode.removeChild(spoilerSpan);
    }
    const innerSpan = spoilerSpan.createEl("span", {
      attr: {
        "aria-hidden": "true"
      }
    });
    function toggleSpoiler() {
      const isRevealed = spoilerSpan.classList.contains("is-revealed");
      if (isRevealed) {
        spoilerSpan.classList.remove("is-revealed");
        spoilerSpan.setAttribute("aria-expanded", "false");
        spoilerSpan.setAttribute("aria-label", "Spoiler, click to reveal");
        innerSpan.setAttribute("aria-hidden", "true");
      } else {
        spoilerSpan.classList.add("is-revealed");
        spoilerSpan.setAttribute("aria-expanded", "true");
        spoilerSpan.removeAttribute("aria-label");
        innerSpan.setAttribute("aria-hidden", "false");
      }
    }
    spoilerSpan.addEventListener("click", () => {
      toggleSpoiler();
    });
    spoilerSpan.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        toggleSpoiler();
      }
    });
    return spoilerSpan;
  }
  const markers = [];
  function insertMarker(parent, node, text, index) {
    const beforeStr = text.slice(0, index);
    const afterStr = text.slice(index + 2);
    if (beforeStr) {
      parent.insertBefore(doc.createTextNode(beforeStr), node);
    }
    const marker = element.createEl("span", {
      attr: { "data-spoiler-marker": "true" }
    });
    if (marker.parentNode) {
      marker.parentNode.removeChild(marker);
    }
    parent.insertBefore(marker, node);
    markers.push(marker);
    if (afterStr) {
      const afterNode = doc.createTextNode(afterStr);
      parent.insertBefore(afterNode, node);
      return afterNode;
    }
    return null;
  }
  function collectMarkers(node) {
    if (node.nodeType === Node.TEXT_NODE) {
      let text = node.nodeValue || "";
      let idx = text.indexOf("||");
      if (idx !== -1 && node.parentNode) {
        const parent = node.parentNode;
        let remainingNode = insertMarker(parent, node, text, idx);
        parent.removeChild(node);
        while (remainingNode) {
          text = remainingNode.nodeValue || "";
          idx = text.indexOf("||");
          if (idx !== -1) {
            const nextRemaining = insertMarker(
              parent,
              remainingNode,
              text,
              idx
            );
            parent.removeChild(remainingNode);
            remainingNode = nextRemaining;
          } else {
            remainingNode = null;
          }
        }
      }
    } else if (node.nodeType === Node.ELEMENT_NODE) {
      const el = node;
      if (el.nodeName === "PRE" || el.nodeName === "CODE") {
        return;
      }
      if (el.classList.contains("note-flow-spoiler") || el.classList.contains("discord-syntax-spoiler")) {
        return;
      }
      for (const child of Array.from(node.childNodes)) {
        collectMarkers(child);
      }
    }
  }
  collectMarkers(element);
  for (let i = 0; i < markers.length - 1; i += 2) {
    const startMarker = markers[i];
    const endMarker = markers[i + 1];
    if (!startMarker || !endMarker) continue;
    const spoilerSpan = createSpoilerSpan();
    let usedRange = false;
    if (typeof doc.createRange === "function") {
      try {
        const range = doc.createRange();
        range.setStartAfter(startMarker);
        range.setEndBefore(endMarker);
        const fragment = range.extractContents();
        spoilerSpan.firstElementChild?.appendChild(fragment);
        if (startMarker.parentNode) {
          startMarker.parentNode.insertBefore(spoilerSpan, startMarker);
          startMarker.parentNode.removeChild(startMarker);
        }
        if (endMarker.parentNode) {
          endMarker.parentNode.removeChild(endMarker);
        }
        markers[i] = null;
        markers[i + 1] = null;
        usedRange = true;
      } catch {
        usedRange = false;
      }
    }
    if (!usedRange) {
      if (startMarker.parentNode && startMarker.parentNode === endMarker.parentNode) {
        const parent = startMarker.parentNode;
        parent.insertBefore(spoilerSpan, startMarker);
        const children = Array.from(parent.childNodes);
        const startIndex = children.indexOf(startMarker);
        const endIndex = children.indexOf(endMarker);
        for (let j = startIndex + 1; j < endIndex; j++) {
          const child = children[j];
          parent.removeChild(child);
          spoilerSpan.firstElementChild?.appendChild(child);
        }
        parent.removeChild(startMarker);
        parent.removeChild(endMarker);
        markers[i] = null;
        markers[i + 1] = null;
      }
    }
  }
  for (const marker of markers) {
    if (marker && marker.parentNode) {
      marker.parentNode.insertBefore(doc.createTextNode("||"), marker);
      marker.parentNode.removeChild(marker);
    }
  }
}

// src/spoiler-detector.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");

// ../core/dist/spoiler.js
function findCodeRanges(text) {
  const codeRanges = [];
  if (!text)
    return codeRanges;
  const lines = text.split("\n");
  let currentOffset = 0;
  let inFence = false;
  let fenceChar = "";
  let fenceLen = 0;
  let fenceStart = 0;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lineStart = currentOffset;
    const lineEnd = currentOffset + line.length;
    const fenceMatch = line.match(/^\s*(`{3,}|~{3,})/);
    if (fenceMatch) {
      const matchStr = fenceMatch[1];
      const char = matchStr[0];
      const len = matchStr.length;
      if (!inFence) {
        inFence = true;
        fenceChar = char;
        fenceLen = len;
        fenceStart = lineStart;
      } else if (char === fenceChar && len >= fenceLen) {
        inFence = false;
        codeRanges.push({ from: fenceStart, to: lineEnd, isFenced: true });
      }
    }
    if (inFence && i === lines.length - 1) {
      codeRanges.push({ from: fenceStart, to: lineEnd, isFenced: true });
    }
    currentOffset = lineEnd + 1;
  }
  currentOffset = 0;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lineStart = currentOffset;
    const lineEnd = currentOffset + line.length;
    const isLineInFence = codeRanges.some((r) => lineStart >= r.from && lineEnd <= r.to);
    if (!isLineInFence) {
      const backtickRegex = /(`+)/g;
      let match;
      let openBacktick = null;
      while ((match = backtickRegex.exec(line)) !== null) {
        const len = match[1].length;
        const index = lineStart + match.index;
        if (!openBacktick) {
          openBacktick = { len, index };
        } else if (openBacktick.len === len) {
          codeRanges.push({
            from: openBacktick.index,
            to: index + len,
            isFenced: false
          });
          openBacktick = null;
        }
      }
    }
    currentOffset = lineEnd + 1;
  }
  return codeRanges;
}
function isPosInCode(pos, codeRanges) {
  return codeRanges.some((r) => pos >= r.from && pos < r.to);
}
function findSpoilerRanges(text, baseOffset = 0) {
  const spoilers = [];
  if (!text || text.length < 5)
    return spoilers;
  const codeRanges = findCodeRanges(text);
  const isCode = (pos) => isPosInCode(pos, codeRanges);
  const delimiterIndices = [];
  let idx = text.indexOf("||");
  while (idx !== -1) {
    if (!isCode(idx) && !isCode(idx + 1)) {
      delimiterIndices.push(idx);
    }
    idx = text.indexOf("||", idx + 2);
  }
  let i = 0;
  while (i < delimiterIndices.length - 1) {
    const startIdx = delimiterIndices[i];
    const endIdx = delimiterIndices[i + 1];
    const content = text.slice(startIdx + 2, endIdx);
    const crossesFencedCode = codeRanges.some((r) => r.isFenced && startIdx < r.from && endIdx > r.to);
    if (!crossesFencedCode && content.length > 0) {
      spoilers.push({
        from: baseOffset + startIdx,
        to: baseOffset + endIdx + 2,
        contentFrom: baseOffset + startIdx + 2,
        contentTo: baseOffset + endIdx
      });
      i += 2;
    } else {
      i += 1;
    }
  }
  return spoilers;
}

// ../core/dist/subtext.js
var SUBTEXT_MARKER = "-# ";
var SUBTEXT_MARKER_LEN = SUBTEXT_MARKER.length;
function isSubtextLine(lineText) {
  return lineText.startsWith(SUBTEXT_MARKER);
}
function stripSubtextPrefix(lineText) {
  if (isSubtextLine(lineText)) {
    return lineText.slice(SUBTEXT_MARKER_LEN);
  }
  return lineText;
}
function hasSubtextMarker(text) {
  return /(?:^|\n)-# /.test(text);
}

// src/spoiler-detector.ts
function getEditorLivePreviewField() {
  try {
    const obs = require("obsidian");
    return obs?.editorLivePreviewField ?? null;
  } catch {
    return null;
  }
}
var setSpoilerStateEffect = import_state.StateEffect.define();
var spoilerStateField = import_state.StateField.define({
  create() {
    return [];
  },
  update(value, tr) {
    let mapped = value.map((entry) => {
      const from = tr.changes.mapPos(entry.from, 1);
      const to = tr.changes.mapPos(entry.to, -1);
      return { ...entry, from, to };
    });
    for (const effect of tr.effects) {
      if (effect.is(setSpoilerStateEffect)) {
        const { from, to, state } = effect.value;
        mapped = mapped.filter(
          (entry) => !(entry.from === from && entry.to === to)
        );
        if (state !== "hidden") {
          mapped.push({ from, to, state });
        }
      }
    }
    return mapped;
  }
});
function getSpoilerState(state, from, to) {
  const livePreviewField = getEditorLivePreviewField();
  if (livePreviewField) {
    const isLivePreview = state.field(livePreviewField, false);
    if (isLivePreview === false) {
      return "revealed";
    }
  }
  const entries = state.field(spoilerStateField, false) || [];
  const match = entries.find((e) => e.from === from && e.to === to);
  if (match) return match.state;
  const overlap = entries.find(
    (e) => Math.max(e.from, from) < Math.min(e.to, to)
  );
  if (overlap) return overlap.state;
  return "hidden";
}
function getSpoilerAtSelection(state) {
  const selection = state.selection;
  if (!selection.main.empty) return null;
  const pos = selection.main.head;
  const line = state.doc.lineAt(pos);
  const spoilers = findSpoilerRanges(line.text, line.from);
  for (const s of spoilers) {
    if (pos >= s.from && pos <= s.to) {
      return s;
    }
  }
  return null;
}
function isRangeInCodeNode(state, from, to) {
  try {
    const tree = syntaxTree(state);
    if (!tree) return false;
    let inCode = false;
    tree.iterate({
      from,
      to,
      enter(node) {
        const name = node.name.toLowerCase();
        if (name.includes("code") || name.includes("comment") || name.includes("math")) {
          inCode = true;
          return false;
        }
      }
    });
    return inCode;
  } catch {
    return false;
  }
}
function getSpoilerFragments(state, contentFrom, contentTo, spoilerIndex = 0) {
  if (contentFrom >= contentTo) return [];
  const pointsSet = /* @__PURE__ */ new Set();
  pointsSet.add(contentFrom);
  pointsSet.add(contentTo);
  const text = state.doc.sliceString(contentFrom, contentTo);
  for (let i = 0; i < text.length; i++) {
    if (text[i] === "\n") {
      const breakPos = contentFrom + i;
      pointsSet.add(breakPos);
      if (breakPos + 1 <= contentTo) {
        pointsSet.add(breakPos + 1);
      }
    }
  }
  try {
    const tree = syntaxTree(state);
    if (tree) {
      tree.iterate({
        from: contentFrom,
        to: contentTo,
        enter(node) {
          if (node.from > contentFrom && node.from < contentTo) {
            pointsSet.add(node.from);
          }
          if (node.to > contentFrom && node.to < contentTo) {
            pointsSet.add(node.to);
          }
        }
      });
    }
  } catch {
  }
  const sortedPoints = Array.from(pointsSet).sort((a, b) => a - b);
  const rawFragments = [];
  for (let i = 0; i < sortedPoints.length - 1; i++) {
    const fFrom = sortedPoints[i];
    const fTo = sortedPoints[i + 1];
    if (fFrom < fTo) {
      const sliceStr = state.doc.sliceString(fFrom, fTo);
      if (sliceStr !== "\n") {
        rawFragments.push({ from: fFrom, to: fTo });
      }
    }
  }
  if (rawFragments.length === 0) {
    return [];
  }
  return rawFragments.map((frag, idx) => {
    const isStart = idx === 0;
    const isEnd = idx === rawFragments.length - 1;
    const classNames = ["note-flow-spoiler", "discord-syntax-spoiler"];
    if (isStart && isEnd) {
      classNames.push(
        "note-flow-spoiler-single",
        "note-flow-spoiler-start",
        "note-flow-spoiler-end",
        "note-flow-spoiler-cap-left",
        "note-flow-spoiler-cap-right",
        "discord-syntax-spoiler-single",
        "discord-syntax-spoiler-start",
        "discord-syntax-spoiler-end",
        "discord-syntax-spoiler-cap-left",
        "discord-syntax-spoiler-cap-right"
      );
    } else if (isStart) {
      classNames.push(
        "note-flow-spoiler-start",
        "note-flow-spoiler-cap-left",
        "discord-syntax-spoiler-start",
        "discord-syntax-spoiler-cap-left"
      );
    } else if (isEnd) {
      classNames.push(
        "note-flow-spoiler-end",
        "note-flow-spoiler-cap-right",
        "discord-syntax-spoiler-end",
        "discord-syntax-spoiler-cap-right"
      );
    }
    classNames.push(`note-flow-spoiler-group-${spoilerIndex}`);
    return {
      from: frag.from,
      to: frag.to,
      isStart,
      isEnd,
      classes: classNames.join(" ")
    };
  });
}
function buildSpoilerDecorations(view) {
  const builder = new import_state.RangeSetBuilder();
  const state = view.state;
  let spoilerIndex = 0;
  for (const { from, to } of view.visibleRanges) {
    const text = state.doc.sliceString(from, to);
    const spoilers = findSpoilerRanges(text, from);
    for (const spoiler of spoilers) {
      spoilerIndex++;
      const spoilerState = getSpoilerState(state, spoiler.from, spoiler.to);
      if (spoilerState === "editing") {
        continue;
      }
      if (isRangeInCodeNode(state, spoiler.from, spoiler.to)) {
        continue;
      }
      const isRevealed = spoilerState === "revealed";
      builder.add(
        spoiler.from,
        spoiler.contentFrom,
        import_view.Decoration.mark({
          class: "note-flow-spoiler-delimiter note-flow-spoiler-hidden discord-syntax-spoiler-delimiter"
        })
      );
      const fragments = getSpoilerFragments(
        state,
        spoiler.contentFrom,
        spoiler.contentTo,
        spoilerIndex
      );
      if (fragments.length > 0) {
        for (const frag of fragments) {
          let classes = frag.classes;
          if (isRevealed) {
            classes += " is-revealed";
          }
          builder.add(
            frag.from,
            frag.to,
            import_view.Decoration.mark({
              class: classes,
              attributes: {
                "data-spoiler-id": `spoiler-${spoiler.from}`
              }
            })
          );
        }
      } else if (spoiler.contentFrom < spoiler.contentTo) {
        let classes = "note-flow-spoiler discord-syntax-spoiler note-flow-spoiler-single note-flow-spoiler-start note-flow-spoiler-end note-flow-spoiler-cap-left note-flow-spoiler-cap-right";
        if (isRevealed) {
          classes += " is-revealed";
        }
        builder.add(
          spoiler.contentFrom,
          spoiler.contentTo,
          import_view.Decoration.mark({
            class: classes,
            attributes: {
              "data-spoiler-id": `spoiler-${spoiler.from}`
            }
          })
        );
      }
      builder.add(
        spoiler.contentTo,
        spoiler.to,
        import_view.Decoration.mark({
          class: "note-flow-spoiler-delimiter note-flow-spoiler-hidden discord-syntax-spoiler-delimiter"
        })
      );
    }
  }
  return builder.finish();
}
var spoilerLivePreviewPlugin = import_view.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.decorations = buildSpoilerDecorations(view);
    }
    update(update) {
      const oldState = update.startState.field(spoilerStateField, false);
      const newState = update.state.field(spoilerStateField, false);
      const stateChanged = oldState !== newState;
      if (update.docChanged || update.selectionSet || update.viewportChanged || stateChanged) {
        this.decorations = buildSpoilerDecorations(update.view);
      }
    }
  },
  {
    decorations: (v) => v.decorations,
    eventHandlers: {
      mousedown(event, view) {
        const livePreviewField = getEditorLivePreviewField();
        if (livePreviewField && view.state.field(livePreviewField, false) === false) return;
        const target = event.target;
        const pos = view.posAtCoords({ x: event.clientX, y: event.clientY });
        if (pos !== null) {
          const line = view.state.doc.lineAt(pos);
          const spoilers = findSpoilerRanges(line.text, line.from);
          const spoiler = spoilers.find((s) => pos >= s.from && pos <= s.to);
          if (spoiler) {
            const currentState = getSpoilerState(
              view.state,
              spoiler.from,
              spoiler.to
            );
            if (currentState === "hidden") {
              event.preventDefault();
              view.dispatch({
                effects: setSpoilerStateEffect.of({
                  from: spoiler.from,
                  to: spoiler.to,
                  state: "revealed"
                })
              });
              return true;
            } else if (currentState === "revealed") {
              event.preventDefault();
              view.dispatch({
                effects: setSpoilerStateEffect.of({
                  from: spoiler.from,
                  to: spoiler.to,
                  state: "editing"
                }),
                selection: { anchor: pos },
                scrollIntoView: true
              });
              view.focus();
              return true;
            } else if (currentState === "editing") {
              event.preventDefault();
              view.dispatch({
                effects: setSpoilerStateEffect.of({
                  from: spoiler.from,
                  to: spoiler.to,
                  state: "hidden"
                }),
                selection: { anchor: spoiler.to },
                scrollIntoView: true
              });
              view.focus();
              return true;
            }
          }
        }
        const spoilerEl = target?.closest?.(
          "[data-spoiler-id]"
        );
        if (spoilerEl) {
          const spoilerId = spoilerEl.getAttribute("data-spoiler-id");
          if (spoilerId) {
            const fromStr = spoilerId.replace("spoiler-", "");
            const from = parseInt(fromStr, 10);
            if (!isNaN(from) && from >= 0 && from <= view.state.doc.length) {
              const line = view.state.doc.lineAt(from);
              const spoilers = findSpoilerRanges(line.text, line.from);
              const spoiler = spoilers.find((s) => s.from === from);
              if (spoiler) {
                const currentState = getSpoilerState(
                  view.state,
                  spoiler.from,
                  spoiler.to
                );
                if (currentState === "hidden") {
                  event.preventDefault();
                  view.dispatch({
                    effects: setSpoilerStateEffect.of({
                      from: spoiler.from,
                      to: spoiler.to,
                      state: "revealed"
                    })
                  });
                  return true;
                } else if (currentState === "revealed") {
                  event.preventDefault();
                  view.dispatch({
                    effects: setSpoilerStateEffect.of({
                      from: spoiler.from,
                      to: spoiler.to,
                      state: "editing"
                    }),
                    selection: { anchor: spoiler.contentFrom },
                    scrollIntoView: true
                  });
                  view.focus();
                  return true;
                }
              }
            }
          }
        }
      },
      keydown(event, view) {
        const livePreviewField = getEditorLivePreviewField();
        if (livePreviewField && view.state.field(livePreviewField, false) === false) return;
        if (event.key === "Enter" || event.key === " ") {
          const spoiler = getSpoilerAtSelection(view.state);
          if (spoiler) {
            const currentState = getSpoilerState(
              view.state,
              spoiler.from,
              spoiler.to
            );
            if (currentState === "hidden") {
              event.preventDefault();
              view.dispatch({
                effects: setSpoilerStateEffect.of({
                  from: spoiler.from,
                  to: spoiler.to,
                  state: "revealed"
                })
              });
              return true;
            } else if (currentState === "revealed") {
              event.preventDefault();
              view.dispatch({
                effects: setSpoilerStateEffect.of({
                  from: spoiler.from,
                  to: spoiler.to,
                  state: "editing"
                }),
                selection: { anchor: spoiler.contentFrom },
                scrollIntoView: true
              });
              view.focus();
              return true;
            } else if (currentState === "editing") {
              event.preventDefault();
              view.dispatch({
                effects: setSpoilerStateEffect.of({
                  from: spoiler.from,
                  to: spoiler.to,
                  state: "hidden"
                }),
                selection: { anchor: spoiler.to },
                scrollIntoView: true
              });
              view.focus();
              return true;
            }
          }
        }
      },
      mouseover(event, view) {
        const target = event.target;
        const spoilerEl = target?.closest?.(
          "[data-spoiler-id]"
        );
        if (!spoilerEl) return;
        const spoilerId = spoilerEl.getAttribute("data-spoiler-id");
        if (!spoilerId || !/^[a-zA-Z0-9_-]+$/.test(spoilerId)) return;
        const relatedTarget = event.relatedTarget;
        const relatedSpoiler = relatedTarget?.closest?.(
          "[data-spoiler-id]"
        );
        const relatedId = relatedSpoiler?.getAttribute("data-spoiler-id");
        if (relatedId === spoilerId) return;
        const elements = view.dom.querySelectorAll(
          `[data-spoiler-id="${spoilerId}"]`
        );
        for (let i = 0; i < elements.length; i++) {
          const el = elements[i];
          if (el instanceof HTMLElement) {
            el.classList.add("is-hovered");
          }
        }
      },
      mouseout(event, view) {
        const target = event.target;
        const spoilerEl = target?.closest?.(
          "[data-spoiler-id]"
        );
        if (!spoilerEl) return;
        const spoilerId = spoilerEl.getAttribute("data-spoiler-id");
        if (!spoilerId || !/^[a-zA-Z0-9_-]+$/.test(spoilerId)) return;
        const relatedTarget = event.relatedTarget;
        const relatedSpoiler = relatedTarget?.closest?.(
          "[data-spoiler-id]"
        );
        const relatedId = relatedSpoiler?.getAttribute("data-spoiler-id");
        if (relatedId === spoilerId) return;
        const elements = view.dom.querySelectorAll(
          `[data-spoiler-id="${spoilerId}"]`
        );
        for (let i = 0; i < elements.length; i++) {
          const el = elements[i];
          if (el instanceof HTMLElement) {
            el.classList.remove("is-hovered");
          }
        }
      }
    }
  }
);
var spoilerLivePreviewExtension = [
  spoilerStateField,
  spoilerLivePreviewPlugin
];

// src/subtext-post-processor.ts
var SUBTEXT_CLASS = "discord-subtext";
function processSubtextParagraph(p) {
  if (!paragraphMightHaveSubtext(p)) return;
  const children = Array.from(p.childNodes);
  const lines = splitIntoLines(children);
  const hasAny = lines.some((line) => lineIsSubtext(line));
  if (!hasAny) return;
  emptyContainer(p);
  for (let li = 0; li < lines.length; li++) {
    const line = lines[li];
    if (line.length === 0) continue;
    if (lineIsSubtext(line)) {
      const clone = cloneLine(line);
      stripMarkerFromFirstText(clone);
      const span = p.createEl("span", { cls: SUBTEXT_CLASS });
      for (const node of clone) span.appendChild(node);
    } else {
      for (const node of line) p.appendChild(node);
    }
  }
}
function emptyContainer(el) {
  const emptyable = el;
  if (typeof emptyable.empty === "function") {
    emptyable.empty();
  } else {
    while (el.firstChild) {
      el.removeChild(el.firstChild);
    }
  }
}
var TEXT_NODE_TYPE = typeof Node !== "undefined" ? Node.TEXT_NODE : 3;
var ELEMENT_NODE_TYPE = typeof Node !== "undefined" ? Node.ELEMENT_NODE : 1;
function paragraphMightHaveSubtext(p) {
  for (const child of Array.from(p.childNodes)) {
    if (child.nodeType === TEXT_NODE_TYPE) {
      const v = child.data;
      if (hasSubtextMarker(v)) return true;
    }
    if (child.nodeType === ELEMENT_NODE_TYPE && child.tagName === "BR") {
      return true;
    }
  }
  return false;
}
function splitIntoLines(nodes) {
  const lines = [[]];
  for (const node of nodes) {
    if (node.nodeType === TEXT_NODE_TYPE) {
      const text = node;
      const parts = text.data.split("\n");
      for (let i = 0; i < parts.length; i++) {
        if (parts[i].length > 0) {
          const frag = text.ownerDocument.createTextNode(parts[i]);
          lines[lines.length - 1].push(frag);
        }
        if (i < parts.length - 1) {
          lines.push([]);
        }
      }
    } else if (node.nodeType === ELEMENT_NODE_TYPE && node.tagName === "BR") {
      lines[lines.length - 1].push(node);
      lines.push([]);
    } else {
      lines[lines.length - 1].push(node);
    }
  }
  return lines;
}
function lineIsSubtext(line) {
  for (const node of line) {
    if (node.nodeType === TEXT_NODE_TYPE) {
      return isSubtextLine(node.data);
    }
    if (node.nodeType === ELEMENT_NODE_TYPE && node.tagName === "BR")
      continue;
    return false;
  }
  return false;
}
function cloneLine(line) {
  return line.map((n) => n.cloneNode(true));
}
function stripMarkerFromFirstText(nodes) {
  for (const node of nodes) {
    if (node.nodeType === TEXT_NODE_TYPE) {
      const t = node;
      if (isSubtextLine(t.data)) {
        t.data = stripSubtextPrefix(t.data);
      }
      return;
    }
    if (node.nodeType === ELEMENT_NODE_TYPE && node.tagName === "BR")
      continue;
    return;
  }
}

// src/subtext-live-preview.ts
var import_view2 = require("@codemirror/view");
var import_state2 = require("@codemirror/state");
var subtextLineMark = import_view2.Decoration.mark({ class: "discord-subtext" });
var subtextMarkerMark = import_view2.Decoration.mark({ class: "discord-subtext-marker" });
var subtextMarkerActiveMark = import_view2.Decoration.mark({
  class: "discord-subtext-marker-active"
});
var subtextEditorPlugin = import_view2.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.decorations = buildDecorations(view);
    }
    update(update) {
      if (update.docChanged || update.viewportChanged || update.selectionSet) {
        this.decorations = buildDecorations(update.view);
      }
    }
  },
  { decorations: (v) => v.decorations }
);
function collectActiveLineNumbers(view) {
  const doc = view.state.doc;
  const active = /* @__PURE__ */ new Set();
  for (const range of view.state.selection.ranges) {
    active.add(doc.lineAt(range.anchor).number);
    active.add(doc.lineAt(range.head).number);
  }
  return active;
}
function buildDecorations(view) {
  const builder = new import_state2.RangeSetBuilder();
  const doc = view.state.doc;
  const activeLines = collectActiveLineNumbers(view);
  for (const { from, to } of view.visibleRanges) {
    const startLine = doc.lineAt(from).number;
    const endLine = doc.lineAt(to).number;
    for (let ln = startLine; ln <= endLine; ln++) {
      const line = doc.line(ln);
      const text = line.text;
      if (!text.startsWith(SUBTEXT_MARKER)) continue;
      const isActive = activeLines.has(ln);
      builder.add(
        line.from,
        line.from + SUBTEXT_MARKER_LEN,
        isActive ? subtextMarkerActiveMark : subtextMarkerMark
      );
      if (line.to > line.from + SUBTEXT_MARKER_LEN) {
        builder.add(line.from + SUBTEXT_MARKER_LEN, line.to, subtextLineMark);
      }
    }
  }
  return builder.finish();
}

// src/main.ts
var DiscordSyntaxPlugin = class extends import_obsidian.Plugin {
  onload() {
    this.registerMarkdownPostProcessor((element) => {
      element.querySelectorAll("p").forEach((p) => {
        processSubtextParagraph(p);
      });
      processSpoilers(element);
    });
    this.registerEditorExtension(subtextEditorPlugin);
    this.registerEditorExtension(spoilerLivePreviewExtension);
    this.addCommand({
      id: "toggle-all-spoilers",
      name: "Toggle all spoilers in active note",
      callback: () => {
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (!activeView) return;
        const mode = activeView.getMode();
        if (mode === "preview") {
          const container = activeView.previewMode?.containerEl;
          if (!container) return;
          const spoilers = container.querySelectorAll(
            ".note-flow-spoiler, .discord-syntax-spoiler"
          );
          if (spoilers.length === 0) return;
          let anyHidden = false;
          for (let i = 0; i < spoilers.length; i++) {
            if (!spoilers[i].classList.contains("is-revealed")) {
              anyHidden = true;
              break;
            }
          }
          const targetReveal = anyHidden;
          for (let i = 0; i < spoilers.length; i++) {
            const el = spoilers[i];
            const inner = el.firstElementChild;
            if (targetReveal) {
              el.classList.add("is-revealed");
              el.setAttribute("aria-expanded", "true");
              el.removeAttribute("aria-label");
              if (inner) inner.setAttribute("aria-hidden", "false");
            } else {
              el.classList.remove("is-revealed");
              el.setAttribute("aria-expanded", "false");
              el.setAttribute("aria-label", "Spoiler, click to reveal");
              if (inner) inner.setAttribute("aria-hidden", "true");
            }
          }
        } else if (mode === "source") {
          const editor = activeView.editor;
          const cm = editor.cm;
          if (!cm || !(cm instanceof import_view3.EditorView) || typeof cm.dispatch !== "function")
            return;
          const state = cm.state;
          const text = state.doc.toString();
          const spoilers = findSpoilerRanges(text);
          if (spoilers.length === 0) return;
          let anyHidden = false;
          for (const s of spoilers) {
            const sState = getSpoilerState(state, s.from, s.to);
            if (sState === "hidden") {
              anyHidden = true;
              break;
            }
          }
          const targetState = anyHidden ? "revealed" : "hidden";
          const effects = spoilers.map(
            (s) => setSpoilerStateEffect.of({
              from: s.from,
              to: s.to,
              state: targetState
            })
          );
          let newSelection;
          if (state.selection.main.empty) {
            const pos = state.selection.main.head;
            for (const s of spoilers) {
              if (pos >= s.from && pos <= s.to) {
                newSelection = { anchor: s.to };
                break;
              }
            }
          }
          cm.dispatch({
            effects,
            selection: newSelection ? { anchor: newSelection.anchor } : void 0
          });
        }
      }
    });
  }
  onunload() {
  }
};
