import esbuild from 'esbuild'
import process from 'process'
import fs from 'fs/promises'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const isWatch = process.argv.includes('--watch')

async function copyReleaseAssets() {
  try {
    const stylesCssSrc = path.join(__dirname, 'src/styles.css')
    const stylesCssDest = path.join(__dirname, 'styles.css')

    if (await fs.stat(stylesCssSrc).catch(() => false)) {
      await fs.copyFile(stylesCssSrc, stylesCssDest)
    }
  } catch (e) {
    console.error('❌ Release asset copy failed:', e.message)
  }
}

const checkExternalPlugin = {
  name: 'check-external-plugin',
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length === 0) {
        try {
          const mainJs = await fs.readFile(path.join(__dirname, 'main.js'), 'utf8')
          const cmModuleRegex = /require\(\s*['"]@codemirror\/(?:state|view|language)['"]\s*\)/
          if (!cmModuleRegex.test(mainJs)) {
            console.error('❌ REGRESSION: CodeMirror runtime modules (state/view/language) are bundled instead of externalized!')
            process.exit(1)
          }
        } catch (e) {
          console.error('❌ Failed to verify bundle:', e.message)
        }
        await copyReleaseAssets()
      }
    })
  }
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/
`

const context = await esbuild.context({
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr'
  ],
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: isWatch ? 'inline' : false,
  treeShaking: true,
  outfile: 'main.js',
  banner: { js: banner },
  define: {
    'process.env.NODE_ENV': JSON.stringify(isWatch ? 'development' : 'production')
  },
  plugins: [checkExternalPlugin]
})

if (isWatch) {
  console.log('⚡ Watching JS & CSS...')
  await context.watch()
} else {
  await context.rebuild()
  await context.dispose()
}
